flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- rfc5051-0.1.0.3
- hs-bibutils-6.6.0.0
- pandoc-2.4
- haddock-library-1.7.0
- HsYAML-0.1.1.2
- texmath-0.11.1.2
- yaml-0.11.0.0
- libyaml-0.1.0.0
- cmark-gfm-0.1.6
- hslua-1.0.1
- hslua-module-text-0.2.0
- skylighting-0.7.4
- skylighting-core-0.7.4
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-12.18
