flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- HsYAML-0.2.0.0
- HsYAML-aeson-0.2.0.0
- haddock-library-1.8.0
- skylighting-0.8.3
- skylighting-core-0.8.3
- regex-pcre-builtin-0.95.0.8.8.35
- doctemplates-0.8
- doclayout-0.2.0.1
- emojis-0.1
- texmath-0.12
- pandoc-types-1.20
- git: 'https://github.com/jgm/pandoc'
  commit: d4c2923025591f7645ca6a3c96570edbf8331e61

ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-14.6
