flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- pandoc-2.7.2
- texmath-0.11.2.2
- skylighting-core-0.7.7
- skylighting-0.7.7
- ipynb-0.1
- cmark-gfm-0.2.0
- doctemplates-0.3
ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-13.9
