flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- pandoc-types-1.17.6.1
- HsYAML-0.2.0.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.7
- doclayout-0.2.0.1
- git: https://github.com/jgm/pandoc.git
  commit: 8f3b3afc70d163afe5e103abec77a4ffafb995bd

ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-14.6
