flags:
  pandoc-citeproc:
    bibutils: true
    embed_data_files: false
    unicode_collation: false
    test_citeproc: false
    debug: false
    static: false
packages:
- '.'
extra-deps:
- HsYAML-0.2.0.0
- HsYAML-aeson-0.2.0.0
- doctemplates-0.6.1
- doclayout-0.1
- git: https://github.com/jgm/pandoc.git
  commit: b64410ff9ce64d6a2c7e09b43694b6f4245f9129

ghc-options:
   "$locals": -fhide-source-paths
resolver: lts-14.6
